server:
  port: 8082

spring:
  application:
    name: cuentas-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:cuentas_db}
    username: ${DB_USER:cuentas_user}
    password: ${DB_PASSWORD:cuentas_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  messaging:
    exchange: clientes.events
    queue: cuentas.clientes.queue
    routing-key-pattern: cliente.*

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.prueba.cuentas: INFO
