server:
  port: 8081

spring:
  application:
    name: personas-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:personas_db}
    username: ${DB_USER:personas_user}
    password: ${DB_PASSWORD:personas_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  messaging:
    exchange: clientes.events
    routing-key-creado: cliente.creado
    routing-key-actualizado: cliente.actualizado
    routing-key-eliminado: cliente.eliminado

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.prueba.personas: INFO
